menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/jhouzi
    GitHub: https://github.com/ibesty
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: tangkunhou
duoshuo:

# Analytics
# google-analytics:
ga: UA-85107697-1

# Copyright Infomation
startyear: 2015
