<<<<<<< HEAD
menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/jhouzi
    GitHub: https://github.com/ibesty
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus: tangkunhou
duoshuo:

# Analytics
# google-analytics:
ga: UA-85107697-1

# Copyright Infomation
startyear: 2015
=======
menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/pinggod
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2015
>>>>>>> 4d1ada90e04d3b4b9de2c4fc3a80aea9539170b1
